### ISSUE TITLE
Fix v6 server-side use of missing APIs

### ISSUE THREAD

**Issue by sgnn7** [cyberark/conjur-oss-suite-release#181] opened 2020-06-25 20:07 UTC
When running the e2e smoketest with Puppet v6 server, we get 500 errors.

Running e2e and monitoring the server container logs, error can be seen here:
```sh-session
2020-06-25 20:02:55,317 ERROR [p.r.core] Internal Server Error: org.jruby.exceptions.NotImplementedError: (NotImplementedError) NotImplementedError
        at RUBY.create_session(/opt/puppetlabs/puppet/lib/ruby/vendor_ruby/puppet/http/external_client.rb:77)
        at RUBY.initialize(/opt/puppetlabs/puppet/lib/ruby/vendor_ruby/puppet/ssl/state_machine.rb:376)
        at RUBY.certificate(/opt/puppetlabs/puppet/lib/ruby/vendor_ruby/puppet/ssl/host.rb:126)
        at RUBY.localhost(/opt/puppetlabs/puppet/lib/ruby/vendor_ruby/puppet/ssl/host.rb:28)
        at RUBY.decrypt(/etc/puppetlabs/code/environments/production/modules/conjur/lib/puppet/functions/conjur/decrypt.rb:11)
```

in this block of code: https://github.com/cyberark/conjur-puppet/blob/v2.0.3/lib/puppet/functions/conjur/decrypt.rb#L11

Relevant block:
```ruby
  def decrypt pkcs7
    host = Puppet::SSL::Host.localhost
    key = host.key.content
    certificate = host.certificate.content
    decryptor = OpenSSL::PKCS7.new pkcs7
    sensitive.new decryptor.decrypt key, certificate
  end
```

**Comment by izgeri** [comment] 2020-06-25 20:34
closing as duplicate of cyberark/conjur-puppet#91

**Closed by izgeri** 2020-06-25 20:34 UTC
Labels: kind/bug, kind/cleanup, kind/enhancement, priority/medium, triage/duplicate
