### ISSUE TITLE
Suite release doesn't parse `+suite.N` version order correctly

### ISSUE THREAD

**Issue by izgeri** [cyberark/conjur-oss-suite-release#208] opened 2021-02-08 15:15 UTC
## Summary
If the last two releases are `1.x.y+suite.1` and `1.x.y+suite.2`, then on the next release `1.{x+1}.y+suite.1`, the changelog automation will compare the new release to `1.x.y+suite.1` (TWO releases ago) instead of `1.x.y+suite.2`.

## Steps to Reproduce
You can see it in #207. If you run the command:
```
summon -p keyring.py   --yaml 'GITHUB_TOKEN: !var github/api_token' \
  ./parse-changelogs \
  -v v1.11.2+suite.1 \
  -t release \
  -o drafts/RELEASE_NOTES.md
```
it compares the new release to `v1.11.1+suite.1` instead of `v1.11.1+suite.2`.

## Expected Results
The new release only includes changes from the current version.

## Actual Results (including error logs, if applicable)
The new release includes the release notes from this version AND the version before.

## Reproducible
   * [x] Always 
   * [ ] Sometimes
   * [ ] Non-Reproducible

## Additional Information
This might be due to semver not considering the build metadata (anything after the `+`) when determining order (see number 10 on semver.org):
> Build metadata MUST be ignored when determining version precedence.

We may need to have custom logic that considers it in our case.

**Comment by doodlesbykumbi** [comment] 2021-02-10 13:13
@izgeri I looked at the source of the semver package and you're right. The semver package entirely stands by this.
> Build metadata MUST be ignored when determining version precedence.

What's the reasoning behind `+suite.{N}`, can that not be done with patch ? There doesn't seem to be a simple fix for this. After a little tinkering it seems that any solution with custom logic would require something like a fork of the semver package. If we can I think we should consider scrapping the idea of using the metadata in anyway that influences version precedence to both be consistent with semver and to benefit from the existent tooling.

**Comment by izgeri** [comment] 2021-02-10 14:44
You can read more about our versioning choice [here](https://github.com/cyberark/conjur-oss-suite-release/blob/master/CONTRIBUTING.md#notes-on-versioning)

This project does not strictly use semver, though it uses a semver-style tagging scheme. The tags in this project are `{Conjur version}+suite.{suite iteration for Conjur version}`.

**Comment by doodlesbykumbi** [comment] 2021-02-10 14:47
Thanks. We can't just take it out then. The approach that comes to mind is to absorb the semver package as internal (it's quite small and I suspect it's only useful here, so it need not be a fork) and change it to take metadata into consideration when making comparisons.

**Comment by doodlesbykumbi** [comment] 2021-02-10 15:37
Some context.

The issue is happening around in this codebase at https://github.com/cyberark/conjur-oss-suite-release/blob/master/pkg/version/version.go#L22. The comparisons don't take metadata into account, even through semver.Version has this info.

We can take the semver package from https://github.com/coreos/go-semver/tree/master/semver and bring it into this codebase (without forking, just straight bring it in). The code we need to change to modify the comparisons is centred around this   https://github.com/coreos/go-semver/blob/master/semver/semver.go#L165. This slice used to make the comparisons. If it can incorporate metadata perhaps by changing the characters to ints and adding them to the slice then maybe that could work.

**Closed** 2021-02-11 03:14 UTC
Labels: component/suite, kind/bug
